((packages  (core))
 (includes  ())
 (libraries ())
 (syntax    (sexplib comparelib pa_ounit))
 (modules   (linear_comb linear linear_regression test_linear test_linear_regression std))
 (target (lib solvers)))
